# what is the goal of the workflow
# Goal : whenegver someone changes the python code, the linter will check if the syntax, format, etc is correct or not
# Test comment for execution
name: Auto Linter

on:
  push: 
    paths: "*.py"

jobs:
  code:
    runs-on: ubuntu-latest
    # This step will automatically clone the code of current branch into tunner
    steps:
      - name: Checkout/clone the code
        uses: actions/checkout@v7 

      # This step will install Linting tool on ubuntu instance
      - name: Install Linter
        run: pip install ruff
  
